### ISSUE TITLE
Docs include the wrong lines from toml files

### ISSUE THREAD

**Issue by bpuchala** [glotzerlab/row#11]
Examples of how to group ("To demonstrate, add the line: ...") in the grouping docs are including the wrong lines. See the beginning of [Sorting Groups](https://row.readthedocs.io/en/0.1.1/guide/tutorial/group.html#sorting-groups).

**Comment by joaander** [comment]
Thanks for reporting this error. The tutorial was previously correct, then `group.include` was changed to an array of tables (#4).

#12 fixes the tutorial.
